### ISSUE TITLE
Scaladex: Add `sound` keyword

### ISSUE THREAD

**Issue by Sciss** [outr/media4s#1]
Just stumbled across the project browsing Scaladex. It would be cool if you added `sound` as a tag in addition to `audio`. I have tagged my things with `sound`:
- https://index.scala-lang.org/search?q=keywords:sound

It would make sense if media4s would appear there, too. It's currently the only entry that uses the `audio` tag:
- https://index.scala-lang.org/search?q=keywords:audio

At some point we might suggest to the Scaladex project to merge tags as aliases, like Stackoverflow does.

**Comment by darkfrog26** [comment]
Thanks for the suggestion. Added `sound` keyword.
