### ISSUE TITLE
Why don't make a functional style wrapper API?

### ISSUE THREAD

**Issue by dev590t** [outr/media4s#7]
Hello, I'm searching a scala library for video processing.
I have discovered the library 'vireo', it is a interested project, but it isn't still maintained.
Then I have discovered this project. I have liked the idea to write a scala wrapper on a popular program. Instead of developer a new scala library from zero. We can have quickly a mature scala library, and easy to maintainer, it isn't the case of 'vireo'

But I have a question about the API of the wrapper.
Functional style allow easily compose few treatments of video. For each operation, the syntax is more elegant, and there is less communication with disk for more performance.
For instance:
```
// with current API
import org.matthicks.media4s.image. ImageUtil._
generateThumbnail(input = new File("a"), output = new File("b"),..)
generateResized(input = new File("b"), output = new File("c"),..)

// with functional style API
val img : Image = load(new File("a"))
img.generateThumbnail(...).generateResized(...).save(new File("c"))
```

Most Scala programmer is functional style programmer, so they prefer use functional style to write elegant code. Why don't make a functional style wrapper API?

**Comment by darkfrog26** [comment]
I'm not opposed to that, and if you're interested in making some code changes and submitting a PR I'd welcome it. This project was mostly hacked together for lack of anything else out there to properly solve my needs. I use it in a few production projects, but I don't have a lot of extra time to maintain it. If you're interested in contributing that would be very welcome. :)

**Comment by dev590t** [comment]
Sorry, but I'm not totally convinced by the CLI wrapper approach used in this project.

To retrieve an information from CLI, most CLI wrapper use regex to parse the output of the command. But the output format of the command can easily change from a version to other. The compiler can't detect it. The program will crash in runtime. A main argument of Scala is robustness of program. But this property can't be satisfied. A wrapper on a librairy API is more robust.
So finally, I have chosen a java multimedia library for my project.

Why you haven't chosen a java library for your projects, if you haven't time to maintain this project? It will be easier for you.

**Comment by darkfrog26** [comment]
I've tried several and they tend to be more buggy, slower, and expose fewer features. I ultimately created my own as a light-weight wrapper because I knew I'd have complete access to all the latest features of the wrapped tool and I can add whatever I need.

**Comment by dev590t** [comment]
>I've tried several and they tend to be more buggy

However, a mature and popular library shouldn't contain many bugs, normally. Can I know what library do you have tested? It is a popular library?

> expose fewer features

I have take a look at the API of 'boofcv'. It uses ffmpeg, but we can't access to all features of ffmpeg thought the class ffmpeg of 'boofcv'. But it is a library design for work on videos, so a mature multimedia library normally it should contains all features expected to work on the video. I feel strange that a mature video library wrapper don't expose a expected feature. Some time, a expected feature is just in a other class. For instance, we can't access to the codec of ffmpeg in `boofcv`, but we have a codec in a other class. I don't see what feature you mean that we can find in CLI tool for video processing, but a video processing library don't have. But if it is the latest feature you mean, a PR should also fix the problem.

I have find [a article on video processing library used in scala project](https://dev.to/darnahsan/video-analytics-in-scala-with-akka-actors-ffmpeg-graphicsmagick-opencv-and-openimaj-2b71)
Actually, I'm still learning 'openimaj', so I can't say if it is better to create a new wrapper scala, or use an existing java wrapper. I will have my response after testing it.

**Comment by darkfrog26** [comment]
I tried nearly everyone that existed at the time. It's funny that you're complaining about a potential problem with media4s, but are you experiencing these problems?  I use media4s for a few commercial projects and it has worked well for my needs for years. If you find something better please let me know.

Can you elaborate on the problems you're experiencing with media4s that makes you want to find something else?

**Comment by dev590t** [comment]
I have never tested media4s. So what I say maybe it would be wrong. It is just based on my quick look at the code. Sorry if I say some errors.

Why I have chosen a other solution?

1. Performance problem: media4s have some performance problem because for each operation, it should communicate with the disk. (explain in my first comment)

2. API elegance problem: We can't compose elegantly each operation. (explain in my first comment)

3. Integration with Scala program isn't perfect. (explain in my previous comment). For instance, we want retrieve a value. But the CLI return an exception. So the parsing will fail, the exception message will be correctly throws in the stack trace? Even if yes, a java library can show until which line in source code the exception is raised.

I think a popular video processing java library cover all feature we can have in media4s, and will not have above problem. I'm convinced above problem can be easily solved in media4s. But if media4s have this problems, it means it is not still mature for me. So I have prefer to use a more mature java library.

**Comment by darkfrog26** [comment]
1.) I doubt you could find a single scenario where this is at all noticeable. I use this library for massive conversions of data and it's crazy fast.
2.) Composability would be a nice add, I just haven't really needed it, so I leave it to others to add if they care.
3.) If you can provide a sample media file that I can reproduce, I can fix it so it better handles errors. This library has derived as I encounter needs.

It's an open-source project, so if there's something better, use it, I won't be offended. :)

**Comment by dev590t** [comment]
Yes :)
